name: Init Swarm
description: Initialize Docker Swarm on manager and join worker nodes

inputs:
  manager_ip:
    description: Manager node public IP
    required: true
  worker_ips:
    description: Comma-separated worker node public IPs
    required: true

runs:
  using: composite
  steps:
    - name: Wait for manager
      shell: bash
      run: |
        echo "Waiting for manager node (SSH + cloud-init + Docker)..."
        for i in $(seq 1 60); do
          if ssh -o ConnectTimeout=5 root@${{ inputs.manager_ip }} \
            "test -f /var/lib/cloud/instance/boot-finished && docker info > /dev/null 2>&1 && echo ready" 2>/tmp/ssh_err.txt | grep -q ready; then
            echo "Manager ready (cloud-init complete, Docker running)"
            break
          fi
          if [ "$i" -eq 60 ]; then
            echo "Manager not ready after 60 attempts"
            echo "Last SSH error:"
            cat /tmp/ssh_err.txt
            # Show cloud-init status if SSH works
            ssh -o ConnectTimeout=5 root@${{ inputs.manager_ip }} \
              "cloud-init status 2>/dev/null; systemctl is-active docker 2>/dev/null" || true
            exit 1
          fi
          if [ $((i % 10)) -eq 0 ]; then
            echo "Attempt $i/60 — $(cat /tmp/ssh_err.txt)"
          else
            echo "Attempt $i/60..."
          fi
          sleep 10
        done

    - name: Initialize Swarm on manager
      shell: bash
      run: |
        PRIVATE_IP=$(ssh root@${{ inputs.manager_ip }} "ip addr show eth1 | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1")
        SWARM_STATE=$(ssh root@${{ inputs.manager_ip }} "docker info --format '{{.Swarm.LocalNodeState}}'" 2>/dev/null || echo "inactive")
        if [ "$SWARM_STATE" = "active" ]; then
          echo "Node is already part of a swarm, skipping init"
        else
          ssh root@${{ inputs.manager_ip }} "docker swarm init --advertise-addr $PRIVATE_IP"
          echo "Swarm initialized with advertise addr: $PRIVATE_IP"
        fi

    - name: Get worker join token
      id: token
      shell: bash
      run: |
        WORKER_TOKEN=$(ssh root@${{ inputs.manager_ip }} "docker swarm join-token worker -q")
        echo "worker_token=$WORKER_TOKEN" >> "$GITHUB_OUTPUT"
        MANAGER_PRIVATE_IP=$(ssh root@${{ inputs.manager_ip }} "ip addr show eth1 | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1")
        echo "manager_private_ip=$MANAGER_PRIVATE_IP" >> "$GITHUB_OUTPUT"

    - name: Join workers
      shell: bash
      run: |
        IFS=',' read -ra WORKERS <<< "${{ inputs.worker_ips }}"
        for WORKER_IP in "${WORKERS[@]}"; do
          echo "Joining worker: $WORKER_IP"
          for i in $(seq 1 60); do
            if ssh -o ConnectTimeout=5 root@$WORKER_IP \
              "test -f /var/lib/cloud/instance/boot-finished && docker info > /dev/null 2>&1 && echo ready" 2>/tmp/ssh_err.txt | grep -q ready; then
              echo "Worker $WORKER_IP ready"
              break
            fi
            if [ "$i" -eq 60 ]; then
              echo "Worker $WORKER_IP not ready after 60 attempts"
              echo "Last SSH error:"
              cat /tmp/ssh_err.txt
              exit 1
            fi
            if [ $((i % 10)) -eq 0 ]; then
              echo "Attempt $i/60 — $(cat /tmp/ssh_err.txt)"
            fi
            sleep 10
          done
          WORKER_SWARM_STATE=$(ssh root@$WORKER_IP "docker info --format '{{.Swarm.LocalNodeState}}'" 2>/dev/null || echo "inactive")
          if [ "$WORKER_SWARM_STATE" = "active" ]; then
            echo "$WORKER_IP is already part of a swarm, skipping join"
          else
            ssh root@$WORKER_IP "docker swarm join --token ${{ steps.token.outputs.worker_token }} ${{ steps.token.outputs.manager_private_ip }}:2377"
            echo "$WORKER_IP joined"
          fi
        done

    - name: Verify swarm
      shell: bash
      run: ssh root@${{ inputs.manager_ip }} "docker node ls"
