name: Init Swarm
description: Initialize Docker Swarm on manager and join worker nodes

inputs:
  manager_ip:
    description: Manager node public IP
    required: true
  worker_ips:
    description: Comma-separated worker node public IPs
    required: true

runs:
  using: composite
  steps:
    - name: Wait for manager
      shell: bash
      run: |
        echo "Waiting for manager node to be ready..."
        for i in $(seq 1 60); do
          if ssh -o ConnectTimeout=5 root@${{ inputs.manager_ip }} "echo ready" 2>/tmp/ssh_err.txt; then
            echo "Manager ready"
            break
          fi
          if [ "$i" -eq 60 ]; then
            echo "Manager not ready after 60 attempts"
            echo "Last SSH error:"
            cat /tmp/ssh_err.txt
            exit 1
          fi
          # Show SSH error every 10 attempts for debugging
          if [ $((i % 10)) -eq 0 ]; then
            echo "Attempt $i/60 — SSH error: $(cat /tmp/ssh_err.txt)"
          else
            echo "Attempt $i/60..."
          fi
          sleep 10
        done

    - name: Initialize Swarm on manager
      shell: bash
      run: |
        PRIVATE_IP=$(ssh root@${{ inputs.manager_ip }} "ip addr show eth1 | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1")
        ssh root@${{ inputs.manager_ip }} "docker swarm init --advertise-addr $PRIVATE_IP"
        echo "Swarm initialized with advertise addr: $PRIVATE_IP"

    - name: Get worker join token
      id: token
      shell: bash
      run: |
        WORKER_TOKEN=$(ssh root@${{ inputs.manager_ip }} "docker swarm join-token worker -q")
        echo "worker_token=$WORKER_TOKEN" >> "$GITHUB_OUTPUT"
        MANAGER_PRIVATE_IP=$(ssh root@${{ inputs.manager_ip }} "ip addr show eth1 | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1")
        echo "manager_private_ip=$MANAGER_PRIVATE_IP" >> "$GITHUB_OUTPUT"

    - name: Join workers
      shell: bash
      run: |
        IFS=',' read -ra WORKERS <<< "${{ inputs.worker_ips }}"
        for WORKER_IP in "${WORKERS[@]}"; do
          echo "Joining worker: $WORKER_IP"
          for i in $(seq 1 60); do
            if ssh -o ConnectTimeout=5 root@$WORKER_IP "echo ready" 2>/tmp/ssh_err.txt; then
              break
            fi
            if [ "$i" -eq 60 ]; then
              echo "Worker $WORKER_IP not ready after 60 attempts"
              echo "Last SSH error:"
              cat /tmp/ssh_err.txt
              exit 1
            fi
            if [ $((i % 10)) -eq 0 ]; then
              echo "Attempt $i/60 — SSH error: $(cat /tmp/ssh_err.txt)"
            fi
            sleep 10
          done
          ssh root@$WORKER_IP "docker swarm join --token ${{ steps.token.outputs.worker_token }} ${{ steps.token.outputs.manager_private_ip }}:2377"
          echo "$WORKER_IP joined"
        done

    - name: Verify swarm
      shell: bash
      run: ssh root@${{ inputs.manager_ip }} "docker node ls"
