name: Registry Login
description: Authenticate to container registry (GHCR, DigitalOcean, or ECR)

inputs:
  registry_type:
    description: Registry type (ghcr, digitalocean, ecr)
    required: false
    default: ghcr
  github_token:
    description: GitHub token for GHCR authentication
    required: false
    default: ''
  github_actor:
    description: GitHub actor for GHCR authentication
    required: false
    default: ''
  do_token:
    description: DigitalOcean token for DO registry
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Login to GHCR
      if: inputs.registry_type == 'ghcr'
      shell: bash
      run: echo "${{ inputs.github_token }}" | docker login ghcr.io -u "${{ inputs.github_actor }}" --password-stdin

    - name: Login to DigitalOcean Registry
      if: inputs.registry_type == 'digitalocean'
      shell: bash
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ inputs.do_token }}
      run: doctl registry login

    - name: Verify login
      shell: bash
      run: echo "Registry login successful (${{ inputs.registry_type }})"
