name: Setup Tools
description: Install Terraform, doctl, and jq for deployment operations

inputs:
  do_token:
    description: DigitalOcean API token for doctl authentication
    required: false
    default: ''
  cloud_provider:
    description: Cloud provider (digitalocean or aws)
    required: false
    default: digitalocean

runs:
  using: composite
  steps:
    - name: Install Terraform
      shell: bash
      run: |
        wget -q -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update -qq
        sudo apt-get install -y -qq terraform

    - name: Install jq
      shell: bash
      run: sudo apt-get install -y -qq jq

    - name: Install doctl (DigitalOcean)
      if: inputs.cloud_provider == 'digitalocean'
      shell: bash
      run: |
        cd /tmp
        wget -q https://github.com/digitalocean/doctl/releases/download/v1.100.0/doctl-1.100.0-linux-amd64.tar.gz
        tar xf doctl-1.100.0-linux-amd64.tar.gz
        sudo mv doctl /usr/local/bin

    - name: Authenticate doctl
      if: inputs.cloud_provider == 'digitalocean' && inputs.do_token != ''
      shell: bash
      run: doctl auth init --access-token "${{ inputs.do_token }}"

    - name: Verify tools
      shell: bash
      run: |
        echo "--- Tool versions ---"
        terraform --version
        jq --version
        if command -v doctl &> /dev/null; then doctl version; fi
