name: Terraform Provision
description: Provision cloud infrastructure using Terraform

inputs:
  cloud_provider:
    description: Cloud provider (digitalocean)
    required: false
    default: digitalocean
  do_token:
    description: DigitalOcean API token
    required: true
  do_spaces_access_key:
    description: DO Spaces access key for Terraform state
    required: true
  do_spaces_secret_key:
    description: DO Spaces secret key for Terraform state
    required: true
  ssh_fingerprint:
    description: SSH key fingerprint registered with the cloud provider
    required: true
  domain:
    description: Domain name for the deployment
    required: true
  stack_name:
    description: Name prefix for all resources
    required: false
    default: staxless
  region:
    description: Cloud region
    required: false
    default: nyc3
  manager_size:
    description: Manager node size
    required: false
    default: s-2vcpu-4gb
  worker_size:
    description: Worker node size
    required: false
    default: s-2vcpu-4gb
  worker_count:
    description: Number of worker nodes
    required: false
    default: '2'
  state_bucket:
    description: S3-compatible bucket for Terraform state
    required: false
    default: staxless-terraform-state
  state_key:
    description: Key path within the state bucket
    required: false
    default: production/terraform.tfstate

outputs:
  manager_ip:
    description: Manager node public IP
    value: ${{ steps.outputs.outputs.manager_ip }}
  manager_private_ip:
    description: Manager node private IP
    value: ${{ steps.outputs.outputs.manager_private_ip }}
  worker_ips:
    description: Comma-separated worker public IPs
    value: ${{ steps.outputs.outputs.worker_ips }}
  worker_private_ips:
    description: Comma-separated worker private IPs
    value: ${{ steps.outputs.outputs.worker_private_ips }}
  all_node_ips:
    description: JSON array of all node public IPs
    value: ${{ steps.outputs.outputs.all_node_ips }}
  vpc_id:
    description: VPC ID
    value: ${{ steps.outputs.outputs.vpc_id }}

runs:
  using: composite
  steps:
    - name: Terraform Init
      shell: bash
      working-directory: ${{ github.action_path }}/../../infrastructure/${{ inputs.cloud_provider }}
      run: |
        terraform init -upgrade \
          -backend-config="access_key=${{ inputs.do_spaces_access_key }}" \
          -backend-config="secret_key=${{ inputs.do_spaces_secret_key }}" \
          -backend-config="bucket=${{ inputs.state_bucket }}" \
          -backend-config="key=${{ inputs.state_key }}"

    - name: Terraform Plan & Apply
      shell: bash
      working-directory: ${{ github.action_path }}/../../infrastructure/${{ inputs.cloud_provider }}
      env:
        TF_VAR_do_token: ${{ inputs.do_token }}
        TF_VAR_ssh_fingerprint: ${{ inputs.ssh_fingerprint }}
        TF_VAR_domain: ${{ inputs.domain }}
        TF_VAR_stack_name: ${{ inputs.stack_name }}
        TF_VAR_region: ${{ inputs.region }}
        TF_VAR_manager_size: ${{ inputs.manager_size }}
        TF_VAR_worker_size: ${{ inputs.worker_size }}
        TF_VAR_worker_count: ${{ inputs.worker_count }}
      run: |
        terraform validate
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan

    - name: Extract Outputs
      id: outputs
      shell: bash
      working-directory: ${{ github.action_path }}/../../infrastructure/${{ inputs.cloud_provider }}
      run: |
        MANAGER_IP=$(terraform output -raw manager_ip)
        MANAGER_PRIVATE_IP=$(terraform output -raw manager_private_ip)
        WORKER_IPS=$(terraform output -json worker_ips | jq -r 'join(",")')
        WORKER_PRIVATE_IPS=$(terraform output -json worker_private_ips | jq -r 'join(",")')
        ALL_NODE_IPS=$(terraform output -json all_node_ips)
        VPC_ID=$(terraform output -raw vpc_id)

        echo "manager_ip=$MANAGER_IP" >> "$GITHUB_OUTPUT"
        echo "manager_private_ip=$MANAGER_PRIVATE_IP" >> "$GITHUB_OUTPUT"
        echo "worker_ips=$WORKER_IPS" >> "$GITHUB_OUTPUT"
        echo "worker_private_ips=$WORKER_PRIVATE_IPS" >> "$GITHUB_OUTPUT"
        echo "all_node_ips=$ALL_NODE_IPS" >> "$GITHUB_OUTPUT"
        echo "vpc_id=$VPC_ID" >> "$GITHUB_OUTPUT"

        echo "Manager IP: $MANAGER_IP"
        echo "Worker IPs: $WORKER_IPS"
