name: Build Images
description: Build and push Docker images using docker buildx bake

inputs:
  services:
    description: Comma-separated list of services to build, or "all"
    required: false
    default: all
  bake_file:
    description: Path to docker-bake.hcl file
    required: false
    default: docker/docker-bake.hcl
  working_directory:
    description: Working directory for the build (consumer repo root)
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push images
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        SERVICES="${{ inputs.services }}"
        BAKE_FILE="${{ inputs.bake_file }}"

        # Run from the bake file's directory so relative context paths resolve correctly
        BAKE_DIR=$(dirname "$BAKE_FILE")
        BAKE_NAME=$(basename "$BAKE_FILE")
        cd "$BAKE_DIR"

        echo "Building images for: $SERVICES"
        echo "Bake file: $BAKE_NAME (in $BAKE_DIR)"

        # Generate override file to label images with source repo.
        # GHCR uses this label to auto-link packages to the repo, which grants
        # GITHUB_TOKEN write access for first-time package creation.
        # (--set can't be used because dots in label keys are parsed as path separators)
        SOURCE_URL="https://github.com/${GITHUB_REPOSITORY}"
        TARGETS=$(docker buildx bake -f "$BAKE_NAME" --print 2>/dev/null | jq -r '.target | keys[]')
        OVERRIDE=""
        for t in $TARGETS; do
          OVERRIDE+="target \"$t\" { labels = { \"org.opencontainers.image.source\" = \"$SOURCE_URL\" } }"$'\n'
        done
        echo "$OVERRIDE" > /tmp/ghcr-labels.hcl
        echo "Adding source label ($SOURCE_URL) to targets: $(echo $TARGETS | tr '\n' ' ')"

        if [ "$SERVICES" = "all" ]; then
          docker buildx bake -f "$BAKE_NAME" -f /tmp/ghcr-labels.hcl \
            --allow=fs.read=.. --push
        else
          IFS=',' read -ra SERVICE_LIST <<< "$SERVICES"
          for service in "${SERVICE_LIST[@]}"; do
            service=$(echo "$service" | xargs)
            echo "Building $service..."
            docker buildx bake -f "$BAKE_NAME" -f /tmp/ghcr-labels.hcl \
              --allow=fs.read=.. --push "$service"
          done
        fi

        echo "Images built and pushed"
