name: Health Check
description: Verify all Docker Swarm services have desired replica counts

inputs:
  manager_ip:
    description: Manager node public IP
    required: true
  wait_seconds:
    description: Seconds to wait before first check
    required: false
    default: '30'
  max_attempts:
    description: Number of health check attempts before failing
    required: false
    default: '10'
  check_interval:
    description: Seconds between health check attempts
    required: false
    default: '30'
  stack_name:
    description: Docker stack name to filter services
    required: false
    default: staxless

runs:
  using: composite
  steps:
    - name: Wait for services to stabilize
      shell: bash
      run: |
        echo "Waiting ${{ inputs.wait_seconds }}s for services to stabilize..."
        sleep ${{ inputs.wait_seconds }}

    - name: Check service health
      shell: bash
      run: |
        MANAGER_IP="${{ inputs.manager_ip }}"
        STACK="${{ inputs.stack_name }}"
        MAX_ATTEMPTS=${{ inputs.max_attempts }}
        CHECK_INTERVAL=${{ inputs.check_interval }}

        for attempt in $(seq 1 "$MAX_ATTEMPTS"); do
          echo "Health check attempt $attempt/$MAX_ATTEMPTS..."

          FAILED=0
          while IFS= read -r line; do
            SERVICE=$(echo "$line" | awk '{print $1}')
            REPLICAS=$(echo "$line" | awk '{print $2}')
            RUNNING=$(echo "$REPLICAS" | cut -d'/' -f1)
            DESIRED=$(echo "$REPLICAS" | cut -d'/' -f2)

            if [ "$RUNNING" != "$DESIRED" ]; then
              echo "  UNHEALTHY: $SERVICE ($RUNNING/$DESIRED replicas)"
              FAILED=1
            else
              echo "  HEALTHY: $SERVICE ($RUNNING/$DESIRED replicas)"
            fi
          done <<< "$(ssh root@"$MANAGER_IP" "docker service ls --filter name=${STACK}_ --format '{{.Name}} {{.Replicas}}'" | grep -v kafka-setup)"

          if [ "$FAILED" -eq 0 ]; then
            echo ""
            echo "All services healthy"
            exit 0
          fi

          if [ "$attempt" -lt "$MAX_ATTEMPTS" ]; then
            echo ""
            echo "Some services not ready, retrying in ${CHECK_INTERVAL}s..."
            echo ""
            sleep "$CHECK_INTERVAL"
          fi
        done

        echo ""
        echo "Services still unhealthy after $MAX_ATTEMPTS attempts ($(( MAX_ATTEMPTS * CHECK_INTERVAL ))s total)"
        echo ""
        echo "Service details:"
        ssh root@"$MANAGER_IP" "docker service ls"

        echo ""
        echo "=== Logs from failing services ==="
        while IFS= read -r line; do
          SERVICE=$(echo "$line" | awk '{print $1}')
          REPLICAS=$(echo "$line" | awk '{print $2}')
          RUNNING=$(echo "$REPLICAS" | cut -d'/' -f1)
          DESIRED=$(echo "$REPLICAS" | cut -d'/' -f2)

          if [ "$RUNNING" != "$DESIRED" ]; then
            echo ""
            echo "--- $SERVICE logs (last 50 lines) ---"
            ssh root@"$MANAGER_IP" "docker service logs --tail 50 --no-trunc $SERVICE 2>&1" || echo "  (no logs available)"
          fi
        done <<< "$(ssh root@"$MANAGER_IP" "docker service ls --filter name=${STACK}_ --format '{{.Name}} {{.Replicas}}'" | grep -v kafka-setup)"

        exit 1
