name: Resolve Config
description: Resolve stack_name and deployment config from .staxless.yml, package.json, or repo name

inputs:
  stack_name:
    description: Explicit stack name override (if non-empty, takes highest priority)
    required: false
    default: ''
  region:
    description: Explicit region override
    required: false
    default: ''
  manager_size:
    description: Explicit manager size override
    required: false
    default: ''
  worker_size:
    description: Explicit worker size override
    required: false
    default: ''
  worker_count:
    description: Explicit worker count override
    required: false
    default: ''
  compose_file:
    description: Explicit compose file override
    required: false
    default: ''
  bake_file:
    description: Explicit bake file override
    required: false
    default: ''

outputs:
  stack_name:
    description: Resolved stack name
    value: ${{ steps.resolve.outputs.stack_name }}
  region:
    description: Resolved region
    value: ${{ steps.resolve.outputs.region }}
  manager_size:
    description: Resolved manager size
    value: ${{ steps.resolve.outputs.manager_size }}
  worker_size:
    description: Resolved worker size
    value: ${{ steps.resolve.outputs.worker_size }}
  worker_count:
    description: Resolved worker count
    value: ${{ steps.resolve.outputs.worker_count }}
  compose_file:
    description: Resolved compose file path
    value: ${{ steps.resolve.outputs.compose_file }}
  bake_file:
    description: Resolved bake file path
    value: ${{ steps.resolve.outputs.bake_file }}

runs:
  using: composite
  steps:
    - name: Resolve configuration
      id: resolve
      shell: bash
      run: |
        python3 - << 'PYTHON_SCRIPT'
        import json
        import os
        import sys

        DEFAULTS = {
            "stack_name": "staxless",
            "region": "nyc3",
            "manager_size": "s-2vcpu-4gb",
            "worker_size": "s-2vcpu-4gb",
            "worker_count": "2",
            "compose_file": "docker/compose/docker-compose.prod.yml",
            "bake_file": "docker/docker-bake.hcl",
        }

        def read_staxless_yml():
            """Read .staxless.yml and return deployment config."""
            config = {}
            for name in [".staxless.yml", ".staxless.yaml"]:
                if not os.path.isfile(name):
                    continue
                try:
                    # Simple YAML parser for flat deployment section
                    with open(name) as f:
                        lines = f.readlines()
                    in_deployment = False
                    for line in lines:
                        stripped = line.strip()
                        if stripped == "" or stripped.startswith("#"):
                            continue
                        # Top-level key (no leading whitespace)
                        if not line[0].isspace() and stripped.endswith(":"):
                            in_deployment = stripped == "deployment:"
                            continue
                        if not line[0].isspace() and ":" in stripped:
                            key, _, val = stripped.partition(":")
                            in_deployment = key.strip() == "deployment"
                            if in_deployment and val.strip():
                                # deployment: {inline} — skip, shouldn't happen
                                continue
                            continue
                        if in_deployment and line[0].isspace() and ":" in stripped:
                            key, _, val = stripped.partition(":")
                            val = val.strip().strip("'\"")
                            if val:
                                config[key.strip()] = val
                    if config:
                        print(f"Config from {name}: {config}", file=sys.stderr)
                        return config
                except Exception as e:
                    print(f"Warning: failed to parse {name}: {e}", file=sys.stderr)
            return config

        def read_package_json_name():
            """Read name from package.json."""
            if not os.path.isfile("package.json"):
                return None
            try:
                with open("package.json") as f:
                    data = json.load(f)
                name = data.get("name", "")
                if name:
                    # Strip scope prefix like @org/name
                    if name.startswith("@") and "/" in name:
                        name = name.split("/", 1)[1]
                    print(f"Package name: {name}", file=sys.stderr)
                    return name
            except Exception as e:
                print(f"Warning: failed to parse package.json: {e}", file=sys.stderr)
            return None

        def repo_name():
            """Extract repo name from GITHUB_REPOSITORY."""
            repo = os.environ.get("GITHUB_REPOSITORY", "")
            if "/" in repo:
                name = repo.split("/", 1)[1]
                print(f"Repo name: {name}", file=sys.stderr)
                return name
            return None

        # Priority chain for stack_name:
        # 1. Explicit input
        # 2. .staxless.yml deployment.stack_name
        # 3. package.json name
        # 4. GitHub repo name
        # 5. Default

        inputs = {
            "stack_name": os.environ.get("INPUT_STACK_NAME", "").strip(),
            "region": os.environ.get("INPUT_REGION", "").strip(),
            "manager_size": os.environ.get("INPUT_MANAGER_SIZE", "").strip(),
            "worker_size": os.environ.get("INPUT_WORKER_SIZE", "").strip(),
            "worker_count": os.environ.get("INPUT_WORKER_COUNT", "").strip(),
            "compose_file": os.environ.get("INPUT_COMPOSE_FILE", "").strip(),
            "bake_file": os.environ.get("INPUT_BAKE_FILE", "").strip(),
        }

        yml_config = read_staxless_yml()
        pkg_name = read_package_json_name()
        fallback_name = repo_name()

        outputs = {}
        for key in DEFAULTS:
            # 1. Explicit input
            if inputs.get(key):
                outputs[key] = inputs[key]
            # 2. .staxless.yml
            elif yml_config.get(key):
                outputs[key] = yml_config[key]
            # 3. package.json name (stack_name only)
            elif key == "stack_name" and pkg_name:
                outputs[key] = pkg_name
            # 4. Repo name (stack_name only)
            elif key == "stack_name" and fallback_name:
                outputs[key] = fallback_name
            # 5. Default
            else:
                outputs[key] = DEFAULTS[key]

        github_output = os.environ.get("GITHUB_OUTPUT", "")
        if github_output:
            with open(github_output, "a") as f:
                for key, val in outputs.items():
                    f.write(f"{key}={val}\n")

        for key, val in outputs.items():
            print(f"Resolved {key}={val}", file=sys.stderr)

        print("Configuration resolved successfully", file=sys.stderr)
        PYTHON_SCRIPT
      env:
        INPUT_STACK_NAME: ${{ inputs.stack_name }}
        INPUT_REGION: ${{ inputs.region }}
        INPUT_MANAGER_SIZE: ${{ inputs.manager_size }}
        INPUT_WORKER_SIZE: ${{ inputs.worker_size }}
        INPUT_WORKER_COUNT: ${{ inputs.worker_count }}
        INPUT_COMPOSE_FILE: ${{ inputs.compose_file }}
        INPUT_BAKE_FILE: ${{ inputs.bake_file }}
