name: Setup SSH
description: Write SSH private key and configure known_hosts for remote access

inputs:
  ssh_private_key:
    description: SSH private key for connecting to droplets
    required: true

runs:
  using: composite
  steps:
    - name: Write SSH key
      shell: bash
      env:
        SSH_KEY: ${{ inputs.ssh_private_key }}
      run: |
        mkdir -p ~/.ssh

        # Write key using Python to reliably handle newline formats
        python3 << 'PYEOF'
        import os
        key = os.environ['SSH_KEY']
        # If key is a single line, convert literal \n to real newlines
        if '\n' not in key:
            key = key.replace('\\n', '\n')
        key = key.strip() + '\n'
        with open(os.path.expanduser('~/.ssh/id_rsa'), 'w') as f:
            f.write(key)
        lines = key.strip().split('\n')
        print(f"Key file lines: {len(lines)}")
        print(f"First line: {lines[0]}")
        print(f"Last line: {lines[-1]}")
        PYEOF

        chmod 600 ~/.ssh/id_rsa

        # Validate key
        ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null 2>/tmp/ssh_key_err.txt || {
          echo "::error::SSH private key is invalid — $(cat /tmp/ssh_key_err.txt)"
          exit 1
        }

    - name: Configure SSH
      shell: bash
      run: |
        cat >> ~/.ssh/config << 'EOF'
        Host *
          StrictHostKeyChecking accept-new
          UserKnownHostsFile ~/.ssh/known_hosts
          ServerAliveInterval 60
          ServerAliveCountMax 3
          ConnectTimeout 10
        EOF
        chmod 600 ~/.ssh/config
