name: Setup SSH
description: Write SSH private key and configure known_hosts for remote access

inputs:
  ssh_private_key:
    description: SSH private key for connecting to droplets
    required: true

runs:
  using: composite
  steps:
    - name: Write SSH key
      shell: bash
      env:
        SSH_KEY: ${{ inputs.ssh_private_key }}
      run: |
        mkdir -p ~/.ssh

        # Write key using Python to reliably handle all newline formats
        python3 << 'PYEOF'
        import os, re
        key = os.environ['SSH_KEY']

        # 1) Convert literal \n sequences to real newlines
        if '\n' not in key:
            key = key.replace('\\n', '\n')

        # 2) If still single-line, reconstruct PEM format from concatenated key
        if key.count('\n') <= 1:
            key = key.strip()
            m = re.match(r'(-----BEGIN [A-Z ]+-----)(.*)(-----END [A-Z ]+-----)', key)
            if m:
                header, body, footer = m.groups()
                body = body.strip()
                lines = [header]
                for i in range(0, len(body), 70):
                    lines.append(body[i:i+70])
                lines.append(footer)
                key = '\n'.join(lines)
                print("Reconstructed PEM format from single-line key")

        key = key.strip() + '\n'
        with open(os.path.expanduser('~/.ssh/id_rsa'), 'w') as f:
            f.write(key)
        lines = key.strip().split('\n')
        print(f"Key file lines: {len(lines)}")
        print(f"First line: {lines[0]}")
        print(f"Last line: {lines[-1]}")
        PYEOF

        chmod 600 ~/.ssh/id_rsa

        # Validate key
        ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null 2>/tmp/ssh_key_err.txt || {
          echo "::error::SSH private key is invalid — $(cat /tmp/ssh_key_err.txt)"
          exit 1
        }

    - name: Configure SSH
      shell: bash
      run: |
        cat >> ~/.ssh/config << 'EOF'
        Host *
          StrictHostKeyChecking accept-new
          UserKnownHostsFile ~/.ssh/known_hosts
          ServerAliveInterval 60
          ServerAliveCountMax 3
          ConnectTimeout 10
        EOF
        chmod 600 ~/.ssh/config
