name: Setup SSH
description: Write SSH private key and configure known_hosts for remote access

inputs:
  ssh_private_key:
    description: SSH private key for connecting to droplets
    required: true

runs:
  using: composite
  steps:
    - name: Write SSH key
      shell: bash
      env:
        SSH_KEY: ${{ inputs.ssh_private_key }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Validate key is readable
        ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null 2>&1 || {
          echo "::error::SSH private key is invalid or malformed"
          exit 1
        }

    - name: Configure SSH
      shell: bash
      run: |
        cat >> ~/.ssh/config << 'EOF'
        Host *
          StrictHostKeyChecking accept-new
          UserKnownHostsFile ~/.ssh/known_hosts
          ServerAliveInterval 60
          ServerAliveCountMax 3
          ConnectTimeout 10
        EOF
        chmod 600 ~/.ssh/config
