name: Setup SSH
description: Write SSH private key and configure known_hosts for remote access

inputs:
  ssh_private_key:
    description: SSH private key for connecting to droplets
    required: true

runs:
  using: composite
  steps:
    - name: Write SSH key
      shell: bash
      env:
        SSH_KEY: ${{ inputs.ssh_private_key }}
      run: |
        mkdir -p ~/.ssh

        # Write key, converting literal \n to real newlines if needed
        echo "$SSH_KEY" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
        # Strip carriage returns and trailing whitespace
        sed -i 's/\r$//' ~/.ssh/id_rsa
        sed -i 's/[[:space:]]*$//' ~/.ssh/id_rsa
        # Ensure file ends with a newline
        sed -i -e '$a\' ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Debug info (safe — no key content exposed)
        echo "Key file lines: $(wc -l < ~/.ssh/id_rsa)"
        echo "First line: $(head -1 ~/.ssh/id_rsa)"
        echo "Last line: $(tail -1 ~/.ssh/id_rsa)"

        # Validate key
        ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null 2>/tmp/ssh_key_err.txt || {
          echo "::error::SSH private key is invalid — $(cat /tmp/ssh_key_err.txt)"
          exit 1
        }

    - name: Configure SSH
      shell: bash
      run: |
        cat >> ~/.ssh/config << 'EOF'
        Host *
          StrictHostKeyChecking accept-new
          UserKnownHostsFile ~/.ssh/known_hosts
          ServerAliveInterval 60
          ServerAliveCountMax 3
          ConnectTimeout 10
        EOF
        chmod 600 ~/.ssh/config
